
volumes:

  default-pg-data-dir-scram:
  default-pg-data-dir-scram-gs:
  
services:

  pg:
    image: 'kartoza/postgis:${TAG:-manual-build}'
    volumes:
      # By default persisted volumes should be in /var/lib/postgresql
      - default-pg-data-dir-scram:/var/lib/postgresql
      - ./tests/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tests:/tests
      - ../utils:/lib/utils
    environment:
      POSTGRES_PASS: 'docker'
      RUN_AS_ROOT: true
    healthcheck:
      interval: 60s
      timeout: 30s
      retries: 3
      test: [ "CMD", "test", "-f", "/tmp/postgres-ready" ]


  
