
volumes:

  default-pg-data-dir-scram:
  default-pg-data-dir-scram-gs:
  
services:


  pg-default-scram:
    image: 'kartoza/postgis:${TAG:-manual-build}'
    volumes:
      # By default persisted volumes should be in /var/lib/postgresql
      - default-pg-data-dir-scram:/var/lib/postgresql
      - ./tests/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tests:/tests
      - ../utils:/lib/utils
    environment:
      POSTGRES_PASS: 'docker'
      RUN_AS_ROOT: true
    healthcheck:
      interval: 60s
      timeout: 30s
      retries: 3
      test: "pg_isready"





  pg-default-scram-gosu:
    image: 'kartoza/postgis:${TAG:-manual-build}'
    volumes:
      # By default persisted volumes should be in /var/lib/postgresql
      - default-pg-data-dir-scram-gs:/var/lib/postgresql
      - ./tests/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tests:/tests
      - ../utils:/lib/utils
    environment:
      POSTGRES_PASS: 'docker'
      RUN_AS_ROOT: false
    healthcheck:
      interval: 60s
      timeout: 30s
      retries: 3
      test: "pg_isready"

  
