name: Feature request
description: Suggest a feature idea for docker-postgis.
labels:
  - 'Feature Request'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request correctly.

  - type: textarea
    id: what
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to happen. Ex. docker-postgis would rock even more if [...]
    validations:
      required: true

  - type: textarea
    id: Additional
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here. Open source is community driven, please consider a way to support this work either by getting a support contract, find someone to submit a pull request.
