name: deploy-image
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - build-latest
    branches:
      - develop
    types:
      - completed

jobs:
  build-local_image:
    runs-on: ubuntu-latest
    if: |
      github.actor != 'dependabot[bot]' &&
      !(
        contains(github.event.pull_request.title, '[skip-release]') ||
        contains(github.event.comment.body, '/skiprelease')
      ) &&
      github.event.workflow_run.conclusion == 'success'
    env:
      latest-ref: refs/heads/develop
    strategy:
      matrix:
        postgresMajorVersion:
          - 18
        postgisMajorVersion:
          - 3
        postgisMinorRelease:
          - 6
        imageVersion:
          - imageDistro: debian
            imageDistroVersion: trixie
            imageDistroVariant: slim

    steps:
      - uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build prod local run image
        id: docker_build_local_run
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          push: false
          tags: kartoza/postgis:prod-build
          outputs: type=docker,dest=/tmp/postgis.tar
          build-args: |
            DISTRO=${{ matrix.imageVersion.imageDistro }}
            IMAGE_VERSION=${{ matrix.imageVersion.imageDistroVersion }}
            IMAGE_VARIANT=${{ matrix.imageVersion.imageDistroVariant }}
            GENERATE_ALL_LOCALE=0
            POSTGRES_MAJOR_VERSION=${{ matrix.postgresMajorVersion }}
            POSTGIS_MAJOR_VERSION=${{ matrix.postgisMajorVersion }}
            POSTGIS_MINOR_VERSION=${{ matrix.postgisMinorRelease }}
          cache-from: |
            type=gha,scope=prod
          target: postgis-prod
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: kartoza-postgis
          path: /tmp/postgis.tar

  deploy-production-images:
    runs-on: ubuntu-latest
    needs: [build-local_image]
    timeout-minutes: 60
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.user.login != 'dependabot[bot]') &&
      github.actor != 'dependabot[bot]' &&
      !(
        contains(github.event.pull_request.title, '[skip-release]') ||
        contains(github.event.comment.body, '/skiprelease')
      )
    strategy:
      matrix:
        postgresMajorVersion:
          - 18
        postgisMajorVersion:
          - 3
        postgisMinorRelease:
          - 6
        postgisPatchMajorVersionBugs:
          - no
        imageVersion:
          - imageDistro: debian
            imageDistroVersion: trixie
            imageDistroVariant: slim

    steps:
      - uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: kartoza-postgis
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/postgis.tar
      - name: Get image versions
        id: pg_image_versions
        run: |
          CONTAINER_NAME=postgis-version-check

          docker run -d \
            --name ${CONTAINER_NAME} \
            kartoza/postgis:prod-build 

          PG_VER=$(docker exec ${CONTAINER_NAME} bash -c \
            "apt-cache policy postgresql-${{ matrix.postgresMajorVersion }} \
            | awk '/Candidate:/ {print \$2}' \
            | sed 's/-.*//'")

          GIS_VER=$(docker exec ${CONTAINER_NAME} bash -c \
            "apt-cache policy postgresql-${{ matrix.postgresMajorVersion }}-postgis-${{ matrix.postgisMajorVersion }} \
            | awk '/Candidate:/ {print \$2}' \
            | sed 's/+.*//' \
            | sed 's/-.*//'")

          docker stop ${CONTAINER_NAME}
          docker rm ${CONTAINER_NAME}

          echo "PG_VER=${PG_VER}" >> $GITHUB_OUTPUT
          echo "GIS_VER=${GIS_VER}" >> $GITHUB_OUTPUT
      - name: Check if generic image tag exists
        id: check_generic_tag
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
          https://hub.docker.com/v2/repositories/kartoza/postgis/tags/${{ matrix.postgresMajorVersion }}-${{ matrix.postgisMajorVersion }}.${{ matrix.postgisMinorRelease }}/)
          echo "check_generic_image=${STATUS}" >> $GITHUB_OUTPUT
      - name: Check if exact image tag exists
        id: check_exact_tag
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
          https://hub.docker.com/v2/repositories/kartoza/postgis/tags/${{ steps.pg_image_versions.outputs.PG_VER }}-${{ steps.pg_image_versions.outputs.GIS_VER }}/)
          echo "check_exact_image=${STATUS}" >> $GITHUB_OUTPUT
      - name: Get Current Date
        id: current_date
        run: echo "formatted=$(date -u +%Y.%m.%d)" >> $GITHUB_OUTPUT
      - name: Build prod image
        id: docker_build_prod
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REPO }}/postgis
            ${{ (steps.check_generic_tag.outputs.check_generic_image == '404' || matrix.postgisPatchMajorVersionBugs == 'yes') && format('{0}/postgis:{1}-{2}.{3}', secrets.DOCKERHUB_REPO, matrix.postgresMajorVersion, matrix.postgisMajorVersion, matrix.postgisMinorRelease) || null }}
            ${{ (steps.check_exact_tag.outputs.check_exact_image == '404' || matrix.postgisPatchMajorVersionBugs == 'yes') && format('{0}/postgis:{1}-{2}', secrets.DOCKERHUB_REPO, steps.pg_image_versions.outputs.PG_VER, steps.pg_image_versions.outputs.GIS_VER) || null }}
            ${{ secrets.DOCKERHUB_REPO }}/postgis:${{ matrix.postgresMajorVersion }}-${{ matrix.postgisMajorVersion }}.${{ matrix.postgisMinorRelease }}--v${{ steps.current_date.outputs.formatted }}
            ${{ secrets.DOCKERHUB_REPO }}/postgis:${{ steps.pg_image_versions.outputs.PG_VER }}-${{ steps.pg_image_versions.outputs.GIS_VER }}--v${{ steps.current_date.outputs.formatted }}
          build-args: |
            DISTRO=${{ matrix.imageVersion.imageDistro }}
            IMAGE_VERSION=${{ matrix.imageVersion.imageDistroVersion }}
            IMAGE_VARIANT=${{ matrix.imageVersion.imageDistroVariant }}
            GENERATE_ALL_LOCALE=1
            POSTGRES_MAJOR_VERSION=${{ matrix.postgresMajorVersion }}
            POSTGIS_MAJOR_VERSION=${{ matrix.postgisMajorVersion }}
            POSTGIS_MINOR_VERSION=${{ matrix.postgisMinorRelease }}
          cache-from: |
            type=gha,scope=prod
          target: postgis-prod

  publish_release_artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: |
      github.actor != 'dependabot[bot]' &&
      !(
        contains(github.event.pull_request.title, '[skip-release]') ||
        contains(github.event.comment.body, '/skiprelease')
      ) &&  github.event.workflow_run.conclusion == 'success'
    needs: [deploy-production-images]
    strategy:
      matrix:
        postgresMajorVersion:
          - 18
        postgisMajorVersion:
          - 3
        postgisMinorRelease:
          - 6
    steps:
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v6
        with:
          ref: 'develop'
      - name: Get Current Date
        id: current_date
        run: echo "formatted=$(date -u +%Y.%m.%d)" >> $GITHUB_OUTPUT
      - name: Get Latest Commit Hash
        id: latest_commit_hash
        run: echo "commit=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
      - name: publish_release
        id: tag_releases
        run: |
          gh release create v${{ matrix.postgresMajorVersion }}.${{ matrix.postgisMajorVersion }}.${{ matrix.postgisMinorRelease }}--v${{ steps.current_date.outputs.formatted }}--${{ steps.latest_commit_hash.outputs.commit }} --notes ${{ steps.latest_commit_hash.outputs.commit }} --target develop --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
